version: '3'
services:
  mongo:
    image: mongo:3.6
  web:
    build: .
    ports:
     - "8081:8081"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/RiseUp
     - /RiseUp/node_modules
     